### ISSUE TITLE
wrong example for TSLint cli usage

### ISSUE THREAD

**Issue by joachimprinzbach** [VismaLietuva/tslint-html-formatter#10]
In the Readme the Usage command for TSLint looks like this:
`tslint --project tsconfig.json --formatters-dir node_modules/tslint-formatter-html/formatters --format html --out tslint.html`

However, your scoped package requires the followin --formatters-dir notation:
`tslint --project tsconfig.json --formatters-dir node_modules/@vismalietuva//tslint-formatter-html/formatters --format html --out t
slint.html`

Scope "@vismalietuva/" is missing. I'll provide a PR.

**Comment by LayZeeDK** [comment]
Thanks @joachimprinzbach. You are right, this changed when the project was published as an NPM package. Take a look at my code comment for your commit.
