### ISSUE TITLE
NPM package

### ISSUE THREAD

**Issue by LayZeeDK** [VismaLietuva/tslint-html-formatter#7]
The next obvious step is to make this project an NPM package.

Can you figure this out, @ramunsk?

**Comment by ramunsk** [comment]
Oh yeah, was thinking about this for a while. Never done this. Will figure. Give me a couple of days

**Comment by ramunsk** [comment]
Done
https://www.npmjs.com/package/@vismalietuva/tslint-formatter-html

**Comment by LayZeeDK** [comment]
Great, @ramunsk!

It is a bit confusing though that this GitHub repository is called `tslint-html-formatter` while the NPM package is called `tslint-formatter-html`.

It seems that `tslint-formatter-html` is the way to go since there are other NPM packages named in a similar way.

Rename the GitHub repository?
